service:
  name: product-service

frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: production
  runtime: nodejs14.x
  profile: app-rs-user
  region: eu-west-1

functions:
  getProductsList:
    handler: index.getProductsListHandler
    events:
      - httpApi:
          method: get
          path: /products
          cors: true
  getProductsById:
    handler: index.getProductsByIdHandler
    events:
      - httpApi:
          method: get
          path: /products/{productId}
          cors: true
