service:
  name: product-service

frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  profile: app-rs-user
  region: eu-west-1

functions:
  getProductsList:
    handler: index.getProductsListHandler
    events:
      - httpApi:
          method: get
          path: /products
          cors: true
  second:
    handler: index.hello
    events:
      - httpApi:
          method: get
          path: /second/{id}
